# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Moscow

# ↓ jekyll-seo-tag settings
title: Yagodzo's Infosec Notes
tagline: 
description: >-
  Заметки по кибербезопасности, TryHackMe, CTF и не только.

url: "https://yagodzo.github.io"

github:
  username: yagodzo

twitter:
  username: # оставьте пустым, если нет Twitter

social:
  name: yagodzo   # Или ваше полное имя, если хотите
  #email:  # расскоментируйте и введите e-mail при желании
  links:
    - https://github.com/yagodzo
    # Добавьте другие соцсети при необходимости

# Site Verification Settings
webmaster_verifications:
  google: X8EHtCAhh7d6uCofR0xkkFAhN3DNO50b9YNGHGjuNhA
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ end of jekyll-seo-tag

analytics:
  google:
    id: G-CLBLN8LQXJ
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode: dark

cdn:

# Аватар: если файл pp.png ещё не заменили на свой, временно оставьте пустым, 
# чтобы не показывать чужую фотографию. Как подготовите – укажите путь.
avatar: # assets/img/pp.png

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: ""

# -------- Не трогайте ниже (технические настройки Chirpy) --------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
